const handleError = async err => {
    console.error(err);
    // await logger.logError(err);
};

module.exports = { handleError };
